<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Page confirmation</title>
</head>
<style>
    #bubble {
        font-size: 25px;
        font-family: Comic Sans MS, Verdana, monospace;
        color: #2d509b;
        font-weight: bold;
    }
</style>
<body>
<div id="bubble">Your email has been verified. Thank you for registering!</div>
</body>

</html>