GET localhost:80/users/1
###
GET localhost:80/podcasts/3
###
GET localhost/users
###

###
###
OPTIONS http://localhost:80/users

#GET http://localhost/papers/search?page=0&size=2&q=не&sort=title

###
GET http://localhost:8080/main/search?page=0&size=2&q=e&sort=title